<?php

namespace AppBundle\Repository;

use Edweld\AclBundle\Doctrine\ACLQueryHelper;
use Doctrine\ORM\EntityRepository;
use Edweld\AclBundle\Entity\Actions;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends EntityRepository
{

    public function findAllWithAcl($user)
    {
        $qb = $this->createQueryBuilder('event');
        ACLQueryHelper::joinACL($qb, $user, Actions::VIEW);
        $q = $qb->getQuery();
        return $q->getResult();
    }

    public function searchAclQuery($user, $term)
    {
    	$qb = $this->createQueryBuilder('event');
    	$qb
    	    ->where($qb->expr()->like('event.name', ':term'))
    	    ->setParameter('term', '%'.$term.'%');

	    ACLQueryHelper::joinACL($qb, $user, Actions::VIEW);
	    return $qb;
    }
}
