# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.acl: 
        class: AppBundle\Service\AclService
        calls:
            - [setContainer, ["@service_container"]]

